/* jshint node: true */
/* global suite, test */
'use strict';

/**
 * @fileoverview The tests run by this file generally compare the triangles
 * generated by the current version of libtess against a known-good version.
 * Note that the comparison is currently strict deep equality, meaning that not
 * only must the vertices be found at the exact same floating-point coordinates,
 * but the triangle vertices must be emitted in the exact same order. This
 * limits optimizations to transformations that change neither by design.
 * Optimizations that do change that output must be much more carefully
 * considered in light of the careful design around numerical precision limits.
 */

var chai = require('chai');
var assert = chai.assert;

var common = require('./common.cjs');
var libtess = common.libtess;
var createTessellator = common.createInstrumentedTessellator;
var tessellate = common.tessellate;

var basetess = require('./expectations/libtess.baseline.cjs');

var rfolder = require('./rfolder.cjs');
var allFiles = rfolder('../data/geometry');
var geometries = Object.keys(allFiles).map(function(filename) {
  return allFiles[filename];
});

var OUTPUT_TYPES = common.OUTPUT_TYPES;
var PROVIDE_NORMAL = common.PROVIDE_NORMAL;
var NORMALS = common.NORMALS;
var WINDING_RULES = common.WINDING_RULES;

suite('Geometry tests', function() {
  for (var i = 0; i < geometries.length; i++) {
    testGeometry(geometries[i]);
  }
});

/**
 * Tests multiple permutations of options in tessellating the provided geometry
 * contours against a baseline (ostensibly correct) tessellator.
 * @param {{name: string, value: !Array.<!Array.<number>>}} geometry
 */
function testGeometry(geometry) {
  suite(geometry.name, function() {

    OUTPUT_TYPES.forEach(function(outputType) {
      suite(outputType.name, function() {

        PROVIDE_NORMAL.forEach(function(provideNormal) {
          suite('using ' + provideNormal.name, function() {

            NORMALS.forEach(function(normal) {
              suite('in the ' + normal.name, function() {

                WINDING_RULES.forEach(function(windingRule) {

                  var baselineTessellator = createTessellator(basetess,
                      outputType);
                  var expectation = tessellate(baselineTessellator,
                      geometry.value, outputType, provideNormal, normal,
                      windingRule);

                  var testDescription = 'should generate correct ' +
                    outputType.name + ' with winding rule ' + windingRule.name;

                  test(testDescription, function() {
                    var tessellator = createTessellator(libtess, outputType);
                    var result = tessellate(tessellator, geometry.value,
                      outputType, provideNormal, normal, windingRule);

                    assert.isArray(result, 'tessellation result not an array');
                    assert.deepEqual(result, expectation,
                        'tessellation result not as expected');
                  });
                });
              });
            });
          });
        });
      });
    });
  });
}
